workflows:
  ios-workflow:
    name: iOS Workflow
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "release/v*"
          include: true
          source: true
      cancel_previous_builds: true
    integrations:
      app_store_connect: lendamobile-22.12.2025
    environment:
      groups:
        - production
      ios_signing:
        distribution_type: app_store # or: ad_hoc | development | enterprise
        bundle_identifier: com.lendasat.lendamobile
      vars:
        BUNDLE_ID: "com.lendasat.lendamobile"
        XCODE_WORKSPACE: "Runner.xcworkspace" # <-- Name of your Xcode workspace
        XCODE_SCHEME: "Runner" # <-- Name of your Xcode scheme
        APP_STORE_APPLE_ID: 6756863835
    scripts:
      - name: Install just
        script: brew install just

      - name: Fetch full git history
        script: git fetch --unshallow || true

      - name: Install Rust
        script: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source "$HOME/.cargo/env"
          rustup target add aarch64-apple-ios

      - name: Install FVM
        script: |
          curl -fsSL https://fvm.app/install.sh | bash -s -- 4.0.5
          echo "$HOME/fvm/bin" >> "$HOME/.bashrc"

      - name: Install flutter_rust_bridge_codegen
        script: |
          source "$HOME/.cargo/env"
          cargo install flutter_rust_bridge_codegen

      - name: Install cargo expand
        script: |
          source "$HOME/.cargo/env"
          cargo install cargo-expand

      - name: Create .env file
        script: |
          cat > .env << EOF
          BACKEND_URL=$BACKEND_URL
          WEBSITE_URL=$WEBSITE_URL
          LENDASAT_API_KEY_SIGNET=$LENDASAT_API_KEY_SIGNET
          LENDASAT_API_KEY_MAINNET=$LENDASAT_API_KEY_MAINNET
          POSTHOG_API_KEY=$POSTHOG_API_KEY
          POSTHOG_HOST=$POSTHOG_HOST
          TURNSTILE_SITE_KEY=$TURNSTILE_SITE_KEY
          TURNSTILE_SECRET_KEY=$TURNSTILE_SECRET_KEY
          TURNSTILE_BASE_URL=$TURNSTILE_BASE_URL
          RAPIDAPI_KEY=$RAPIDAPI_KEY
          ARK_SERVER_URL=$ARK_SERVER_URL
          ESPLORA_URL=$ESPLORA_URL
          ARK_NETWORK=$ARK_NETWORK
          BOLTZ_URL=$BOLTZ_URL
          EOF

      - name: Install Flutter dependencies
        script: |
          export PATH="$HOME/fvm/bin:$PATH"
          fvm flutter pub get

      - name: Precache Flutter iOS artifacts
        script: |
          export PATH="$HOME/fvm/bin:$PATH"
          fvm flutter precache --ios

      - name: Install CocoaPods dependencies
        script: cd ios && pod install

      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles

      - name: Build FFI bindings
        script: |
          source "$HOME/.cargo/env"
          export PATH="$HOME/fvm/bin:$PATH"
          just ffi-build

      - name: Build Rust for iOS
        script: |
          source "$HOME/.cargo/env"
          just ios-build

      - name: Build ipa for distribution
        script: |
          export PATH="$HOME/fvm/bin:$PATH"

          just -f common.just check-env

          BUILD_NAME=$(yq -r .version pubspec.yaml)
          BUILD_NUMBER=$(git rev-list --count HEAD)

          echo "Building ip version ${BUILD_NAME} and build number ${BUILD_NUMBER}"

          fvm flutter build ipa \
            --release \
            --build-name=$BUILD_NAME \
            --build-number=$BUILD_NUMBER \
            --dart-define=ESPLORA_URL=$ESPLORA_URL \
            --dart-define=ARK_SERVER_URL=$ARK_SERVER_URL \
            --dart-define=ARK_NETWORK=$ARK_NETWORK \
            --dart-define=BOLTZ_URL=$BOLTZ_URL \
            --dart-define=BACKEND_URL=$BACKEND_URL \
            --dart-define=WEBSITE_URL=$WEBSITE_URL \
            --dart-define=LENDASAT_API_KEY_SIGNET=$LENDASAT_API_KEY_SIGNET \
            --dart-define=LENDASAT_API_KEY_MAINNET=$LENDASAT_API_KEY_MAINNET \
            --dart-define=POSTHOG_API_KEY=$POSTHOG_API_KEY \
            --dart-define=POSTHOG_HOST=$POSTHOG_HOST \
            --dart-define=TURNSTILE_SITE_KEY=$TURNSTILE_SITE_KEY \
            --dart-define=TURNSTILE_BASE_URL=$TURNSTILE_BASE_URL \
            --dart-define=RAPIDAPI_KEY=$RAPIDAPI_KEY \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - philipp@lendasat.com
        notify:
          success: true
          failure: true

      app_store_connect:
        # Use referenced App Store Connect API key to authenticate binary upload
        auth: integration

        # Configuration related to TestFlight (optional)

        # Optional boolean, defaults to false. Whether or not to submit the uploaded
        # build to TestFlight beta review. Required for distributing to beta groups.
        # Note: This action is performed during post-processing.
        submit_to_testflight: true

        # Optional boolean, defaults to false. Set to true to automatically expire
        # previous build in review or waiting for review in Testflight before
        # submitting a new build to beta review. Expired builds will no longer be available for testers.
        # Note: This action is performed during post-processing.
        expire_build_submitted_for_review: false

        # Configuration related to App Store (optional)

        # Optional boolean, defaults to false. Whether or not to submit the uploaded
        # build to App Store review. Note: This action is performed during post-processing.
        submit_to_app_store: false
  android-workflow:
    name: Android Release Workflow
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "release/v*"
          include: true
          source: true
      cancel_previous_builds: true
    environment:
      android_signing:
        - lendamobile-android-keystore
      groups:
        - production
      vars:
        PACKAGE_NAME: "com.lendasat.lendamobile"
        GOOGLE_PLAY_TRACK: beta
    scripts:
      - name: Install just
        script: brew install just

      - name: Fetch full git history
        script: git fetch --unshallow || true

      - name: Install Rust
        script: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source "$HOME/.cargo/env"
          rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android i686-linux-android

      - name: Install cargo-ndk
        script: |
          source "$HOME/.cargo/env"
          cargo install cargo-ndk

      - name: Install FVM
        script: |
          curl -fsSL https://fvm.app/install.sh | bash -s -- 4.0.5
          echo "$HOME/fvm/bin" >> "$HOME/.bashrc"

      - name: Install cargo expand
        script: |
          source "$HOME/.cargo/env"
          cargo install cargo-expand

      - name: Create .env file
        script: |
          cat > .env << EOF
          BACKEND_URL=$BACKEND_URL
          WEBSITE_URL=$WEBSITE_URL
          LENDASAT_API_KEY_SIGNET=$LENDASAT_API_KEY_SIGNET
          LENDASAT_API_KEY_MAINNET=$LENDASAT_API_KEY_MAINNET
          POSTHOG_API_KEY=$POSTHOG_API_KEY
          POSTHOG_HOST=$POSTHOG_HOST
          TURNSTILE_SITE_KEY=$TURNSTILE_SITE_KEY
          TURNSTILE_SECRET_KEY=$TURNSTILE_SECRET_KEY
          TURNSTILE_BASE_URL=$TURNSTILE_BASE_URL
          RAPIDAPI_KEY=$RAPIDAPI_KEY
          ARK_SERVER_URL=$ARK_SERVER_URL
          ESPLORA_URL=$ESPLORA_URL
          ARK_NETWORK=$ARK_NETWORK
          BOLTZ_URL=$BOLTZ_URL
          EOF

      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"

      - name: Install Flutter dependencies
        script: |
          export PATH="$HOME/fvm/bin:$PATH"
          fvm flutter pub get

      - name: Install flutter_rust_bridge_codegen
        script: |
          source "$HOME/.cargo/env"
          cargo install flutter_rust_bridge_codegen

      - name: Build FFI bindings
        script: |
          source "$HOME/.cargo/env"
          export PATH="$HOME/fvm/bin:$PATH"
          just ffi-build

      - name: Build Rust for android
        script: |
          source "$HOME/.cargo/env"
          just android-build

      - name: Build android release bundle
        script: |
          export PATH="$HOME/fvm/bin:$PATH"

          just -f common.just check-env

          BUILD_NAME=$(yq -r .version pubspec.yaml)
          BUILD_NUMBER=$(git rev-list --count HEAD)

          echo "Building appbundle version ${BUILD_NAME} and build number ${BUILD_NUMBER}"

          fvm flutter build appbundle \
          --release \
          --build-name=$BUILD_NAME \
          --build-number=$BUILD_NUMBER \
          --dart-define=ESPLORA_URL=$ESPLORA_URL \
          --dart-define=ARK_SERVER_URL=$ARK_SERVER_URL \
          --dart-define=ARK_NETWORK=$ARK_NETWORK \
          --dart-define=BOLTZ_URL=$BOLTZ_URL \
          --dart-define=BACKEND_URL=$BACKEND_URL \
          --dart-define=WEBSITE_URL=$WEBSITE_URL \
          --dart-define=LENDASAT_API_KEY_SIGNET=$LENDASAT_API_KEY_SIGNET \
          --dart-define=LENDASAT_API_KEY_MAINNET=$LENDASAT_API_KEY_MAINNET \
          --dart-define=POSTHOG_API_KEY=$POSTHOG_API_KEY \
          --dart-define=POSTHOG_HOST=$POSTHOG_HOST \
          --dart-define=TURNSTILE_SITE_KEY=$TURNSTILE_SITE_KEY \
          --dart-define=TURNSTILE_BASE_URL=$TURNSTILE_BASE_URL \
          --dart-define=RAPIDAPI_KEY=$RAPIDAPI_KEY

          echo "You can now manually upload the bundle file"

    publishing:
      email:
        recipients:
          - philipp@lendasat.com
        notify:
          success: true
          failure: false
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS
        #  ┌────────────┬──────────────────────────┐
        #  │   Track    │ Google Play Console Name │
        #  ├────────────┼──────────────────────────┤
        #  │ internal   │ Internal testing         │
        #  ├────────────┼──────────────────────────┤
        #  │ alpha      │ Closed testing           │
        #  ├────────────┼──────────────────────────┤
        #  │ beta       │ Open testing             │
        #  ├────────────┼──────────────────────────┤
        #  │ production │ Production               │
        track: beta
        submit_as_draft: true
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
