workflows:
  ios-workflow:
    name: iOS Workflow
    integrations:
      app_store_connect: lendamobile-22.12.2025
    environment:
      ios_signing:
        distribution_type: app_store # or: ad_hoc | development | enterprise
        bundle_identifier: com.lendasat.lendamobile
      vars:
        BUNDLE_ID: "com.lendasat.lendamobile"
        XCODE_WORKSPACE: "Runner.xcworkspace" # <-- Name of your Xcode workspace
        XCODE_SCHEME: "Runner" # <-- Name of your Xcode scheme
        APP_STORE_APPLE_ID: 6756863835
    scripts:
      # Install Rust toolchain
      - name: Install Rust
        script: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source "$HOME/.cargo/env"
          rustup target add aarch64-apple-ios

      # Install flutter_rust_bridge_codegen
      - name: Install flutter_rust_bridge_codegen
        script: |
          source "$HOME/.cargo/env"
          cargo install flutter_rust_bridge_codegen
      # Install cargo expand
      - name: Install cargo expand
        script: |
          source "$HOME/.cargo/env"
          cargo install cargo-expand

      # Generate FFI bindings (equivalent to: just ffi-build)
      - name: Generate FFI bindings
        script: |
          source "$HOME/.cargo/env"
          flutter_rust_bridge_codegen generate

      # Build Rust for iOS (equivalent to: just ios-build)
      - name: Build Rust for iOS
        script: |
          source "$HOME/.cargo/env"
          cd rust && cargo build --release --target aarch64-apple-ios

      # Flutter dependencies
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install

      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles

      - name: Increment build number
        script: |
          cd $CM_BUILD_DIR/ios
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))

      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - philipp@lendasat.com
        notify:
          success: true
          failure: true

      app_store_connect:
        # Use referenced App Store Connect API key to authenticate binary upload
        auth: integration

        # Configuration related to TestFlight (optional)

        # Optional boolean, defaults to false. Whether or not to submit the uploaded
        # build to TestFlight beta review. Required for distributing to beta groups.
        # Note: This action is performed during post-processing.
        submit_to_testflight: true

        # Optional boolean, defaults to false. Set to true to automatically expire
        # previous build in review or waiting for review in Testflight before
        # submitting a new build to beta review. Expired builds will no longer be available for testers.
        # Note: This action is performed during post-processing.
        expire_build_submitted_for_review: false

        # Specify the names of beta tester groups that will get access to the build
        # once it has passed beta review.
        beta_groups:
          - beta

        # Configuration related to App Store (optional)

        # Optional boolean, defaults to false. Whether or not to submit the uploaded
        # build to App Store review. Note: This action is performed during post-processing.
        submit_to_app_store: false