// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'logger.dart';
import 'models/exchange_rates.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Stream<LogEntry> initLogging() => RustLib.instance.api.crateApiInitLogging();

/// Fetch current exchange rates from USD to various fiat currencies
Future<ExchangeRates> fetchExchangeRates() =>
    RustLib.instance.api.crateApiFetchExchangeRates();

/// Get all supported fiat currencies
List<FiatCurrency> getSupportedCurrencies() =>
    RustLib.instance.api.crateApiGetSupportedCurrencies();

/// Get currency code for a given currency
String currencyCode({required FiatCurrency currency}) =>
    RustLib.instance.api.crateApiCurrencyCode(currency: currency);
