// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'api/ark_api.dart';
import 'api/bitcoin_api.dart';
import 'api/mempool_api.dart';
import 'api/mempool_block_tracker.dart';
import 'api/mempool_ws.dart';
import 'api/moonpay_api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'logger.dart';
import 'models/exchange_rates.dart';
import 'models/historical_prices.dart';
import 'models/mempool.dart';
import 'models/moonpay.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  Map<String, double> dco_decode_Map_String_f_64_None(dynamic raw);

  @protected
  RustStreamSink<LogEntry> dco_decode_StreamSink_log_entry_Sse(dynamic raw);

  @protected
  RustStreamSink<MempoolWsMessage> dco_decode_StreamSink_mempool_ws_message_Sse(
      dynamic raw);

  @protected
  RustStreamSink<ProjectedBlockTransactions>
      dco_decode_StreamSink_projected_block_transactions_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  Addresses dco_decode_addresses(dynamic raw);

  @protected
  Balance dco_decode_balance(dynamic raw);

  @protected
  BitcoinTransaction dco_decode_bitcoin_transaction(dynamic raw);

  @protected
  Block dco_decode_block(dynamic raw);

  @protected
  BlockExtras dco_decode_block_extras(dynamic raw);

  @protected
  BoltzSwap dco_decode_boltz_swap(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BlockExtras dco_decode_box_autoadd_block_extras(dynamic raw);

  @protected
  BoltzSwap dco_decode_box_autoadd_boltz_swap(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  Conversions dco_decode_box_autoadd_conversions(dynamic raw);

  @protected
  DifficultyAdjustment dco_decode_box_autoadd_difficulty_adjustment(
      dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  FearGreedData dco_decode_box_autoadd_fear_greed_data(dynamic raw);

  @protected
  FearGreedLastUpdated dco_decode_box_autoadd_fear_greed_last_updated(
      dynamic raw);

  @protected
  FearGreedValue dco_decode_box_autoadd_fear_greed_value(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  MiningPool dco_decode_box_autoadd_mining_pool(dynamic raw);

  @protected
  RecommendedFees dco_decode_box_autoadd_recommended_fees(dynamic raw);

  @protected
  TxOutput dco_decode_box_autoadd_tx_output(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  Conversions dco_decode_conversions(dynamic raw);

  @protected
  CurrencyInfo dco_decode_currency_info(dynamic raw);

  @protected
  DifficultyAdjustment dco_decode_difficulty_adjustment(dynamic raw);

  @protected
  DifficultyPoint dco_decode_difficulty_point(dynamic raw);

  @protected
  ExchangeRates dco_decode_exchange_rates(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FearGreedData dco_decode_fear_greed_data(dynamic raw);

  @protected
  FearGreedIndex dco_decode_fear_greed_index(dynamic raw);

  @protected
  FearGreedLastUpdated dco_decode_fear_greed_last_updated(dynamic raw);

  @protected
  FearGreedValue dco_decode_fear_greed_value(dynamic raw);

  @protected
  FiatCurrency dco_decode_fiat_currency(dynamic raw);

  @protected
  HashrateData dco_decode_hashrate_data(dynamic raw);

  @protected
  HashratePoint dco_decode_hashrate_point(dynamic raw);

  @protected
  HistoricalPriceData dco_decode_historical_price_data(dynamic raw);

  @protected
  HistoricalPriceResponse dco_decode_historical_price_response(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  Info dco_decode_info(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<BitcoinTransaction> dco_decode_list_bitcoin_transaction(dynamic raw);

  @protected
  List<Block> dco_decode_list_block(dynamic raw);

  @protected
  List<DifficultyPoint> dco_decode_list_difficulty_point(dynamic raw);

  @protected
  List<FiatCurrency> dco_decode_list_fiat_currency(dynamic raw);

  @protected
  List<HashratePoint> dco_decode_list_hashrate_point(dynamic raw);

  @protected
  List<HistoricalPriceData> dco_decode_list_historical_price_data(dynamic raw);

  @protected
  List<MempoolBlock> dco_decode_list_mempool_block(dynamic raw);

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProjectedTransaction> dco_decode_list_projected_transaction(dynamic raw);

  @protected
  List<(String, double)> dco_decode_list_record_string_f_64(dynamic raw);

  @protected
  List<Transaction> dco_decode_list_transaction(dynamic raw);

  @protected
  List<TxInput> dco_decode_list_tx_input(dynamic raw);

  @protected
  List<TxOutput> dco_decode_list_tx_output(dynamic raw);

  @protected
  LnPaymentResult dco_decode_ln_payment_result(dynamic raw);

  @protected
  LogEntry dco_decode_log_entry(dynamic raw);

  @protected
  MempoolBlock dco_decode_mempool_block(dynamic raw);

  @protected
  MempoolWsMessage dco_decode_mempool_ws_message(dynamic raw);

  @protected
  MiningPool dco_decode_mining_pool(dynamic raw);

  @protected
  MoonPayCurrencyLimits dco_decode_moon_pay_currency_limits(dynamic raw);

  @protected
  MoonPayEncryptedData dco_decode_moon_pay_encrypted_data(dynamic raw);

  @protected
  MoonPayQuote dco_decode_moon_pay_quote(dynamic raw);

  @protected
  OffchainBalance dco_decode_offchain_balance(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  BlockExtras? dco_decode_opt_box_autoadd_block_extras(dynamic raw);

  @protected
  BoltzSwap? dco_decode_opt_box_autoadd_boltz_swap(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  Conversions? dco_decode_opt_box_autoadd_conversions(dynamic raw);

  @protected
  DifficultyAdjustment? dco_decode_opt_box_autoadd_difficulty_adjustment(
      dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  FearGreedData? dco_decode_opt_box_autoadd_fear_greed_data(dynamic raw);

  @protected
  FearGreedLastUpdated? dco_decode_opt_box_autoadd_fear_greed_last_updated(
      dynamic raw);

  @protected
  FearGreedValue? dco_decode_opt_box_autoadd_fear_greed_value(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  MiningPool? dco_decode_opt_box_autoadd_mining_pool(dynamic raw);

  @protected
  RecommendedFees? dco_decode_opt_box_autoadd_recommended_fees(dynamic raw);

  @protected
  TxOutput? dco_decode_opt_box_autoadd_tx_output(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  List<Block>? dco_decode_opt_list_block(dynamic raw);

  @protected
  List<MempoolBlock>? dco_decode_opt_list_mempool_block(dynamic raw);

  @protected
  PaymentReceived dco_decode_payment_received(dynamic raw);

  @protected
  ProjectedBlockTransactions dco_decode_projected_block_transactions(
      dynamic raw);

  @protected
  ProjectedTransaction dco_decode_projected_transaction(dynamic raw);

  @protected
  RecommendedFees dco_decode_recommended_fees(dynamic raw);

  @protected
  (String, double) dco_decode_record_string_f_64(dynamic raw);

  @protected
  Transaction dco_decode_transaction(dynamic raw);

  @protected
  TxInput dco_decode_tx_input(dynamic raw);

  @protected
  TxOutput dco_decode_tx_output(dynamic raw);

  @protected
  TxStatus dco_decode_tx_status(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Map<String, double> sse_decode_Map_String_f_64_None(
      SseDeserializer deserializer);

  @protected
  RustStreamSink<LogEntry> sse_decode_StreamSink_log_entry_Sse(
      SseDeserializer deserializer);

  @protected
  RustStreamSink<MempoolWsMessage> sse_decode_StreamSink_mempool_ws_message_Sse(
      SseDeserializer deserializer);

  @protected
  RustStreamSink<ProjectedBlockTransactions>
      sse_decode_StreamSink_projected_block_transactions_Sse(
          SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  Addresses sse_decode_addresses(SseDeserializer deserializer);

  @protected
  Balance sse_decode_balance(SseDeserializer deserializer);

  @protected
  BitcoinTransaction sse_decode_bitcoin_transaction(
      SseDeserializer deserializer);

  @protected
  Block sse_decode_block(SseDeserializer deserializer);

  @protected
  BlockExtras sse_decode_block_extras(SseDeserializer deserializer);

  @protected
  BoltzSwap sse_decode_boltz_swap(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BlockExtras sse_decode_box_autoadd_block_extras(SseDeserializer deserializer);

  @protected
  BoltzSwap sse_decode_box_autoadd_boltz_swap(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  Conversions sse_decode_box_autoadd_conversions(SseDeserializer deserializer);

  @protected
  DifficultyAdjustment sse_decode_box_autoadd_difficulty_adjustment(
      SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  FearGreedData sse_decode_box_autoadd_fear_greed_data(
      SseDeserializer deserializer);

  @protected
  FearGreedLastUpdated sse_decode_box_autoadd_fear_greed_last_updated(
      SseDeserializer deserializer);

  @protected
  FearGreedValue sse_decode_box_autoadd_fear_greed_value(
      SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  MiningPool sse_decode_box_autoadd_mining_pool(SseDeserializer deserializer);

  @protected
  RecommendedFees sse_decode_box_autoadd_recommended_fees(
      SseDeserializer deserializer);

  @protected
  TxOutput sse_decode_box_autoadd_tx_output(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  Conversions sse_decode_conversions(SseDeserializer deserializer);

  @protected
  CurrencyInfo sse_decode_currency_info(SseDeserializer deserializer);

  @protected
  DifficultyAdjustment sse_decode_difficulty_adjustment(
      SseDeserializer deserializer);

  @protected
  DifficultyPoint sse_decode_difficulty_point(SseDeserializer deserializer);

  @protected
  ExchangeRates sse_decode_exchange_rates(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FearGreedData sse_decode_fear_greed_data(SseDeserializer deserializer);

  @protected
  FearGreedIndex sse_decode_fear_greed_index(SseDeserializer deserializer);

  @protected
  FearGreedLastUpdated sse_decode_fear_greed_last_updated(
      SseDeserializer deserializer);

  @protected
  FearGreedValue sse_decode_fear_greed_value(SseDeserializer deserializer);

  @protected
  FiatCurrency sse_decode_fiat_currency(SseDeserializer deserializer);

  @protected
  HashrateData sse_decode_hashrate_data(SseDeserializer deserializer);

  @protected
  HashratePoint sse_decode_hashrate_point(SseDeserializer deserializer);

  @protected
  HistoricalPriceData sse_decode_historical_price_data(
      SseDeserializer deserializer);

  @protected
  HistoricalPriceResponse sse_decode_historical_price_response(
      SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  Info sse_decode_info(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<BitcoinTransaction> sse_decode_list_bitcoin_transaction(
      SseDeserializer deserializer);

  @protected
  List<Block> sse_decode_list_block(SseDeserializer deserializer);

  @protected
  List<DifficultyPoint> sse_decode_list_difficulty_point(
      SseDeserializer deserializer);

  @protected
  List<FiatCurrency> sse_decode_list_fiat_currency(
      SseDeserializer deserializer);

  @protected
  List<HashratePoint> sse_decode_list_hashrate_point(
      SseDeserializer deserializer);

  @protected
  List<HistoricalPriceData> sse_decode_list_historical_price_data(
      SseDeserializer deserializer);

  @protected
  List<MempoolBlock> sse_decode_list_mempool_block(
      SseDeserializer deserializer);

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProjectedTransaction> sse_decode_list_projected_transaction(
      SseDeserializer deserializer);

  @protected
  List<(String, double)> sse_decode_list_record_string_f_64(
      SseDeserializer deserializer);

  @protected
  List<Transaction> sse_decode_list_transaction(SseDeserializer deserializer);

  @protected
  List<TxInput> sse_decode_list_tx_input(SseDeserializer deserializer);

  @protected
  List<TxOutput> sse_decode_list_tx_output(SseDeserializer deserializer);

  @protected
  LnPaymentResult sse_decode_ln_payment_result(SseDeserializer deserializer);

  @protected
  LogEntry sse_decode_log_entry(SseDeserializer deserializer);

  @protected
  MempoolBlock sse_decode_mempool_block(SseDeserializer deserializer);

  @protected
  MempoolWsMessage sse_decode_mempool_ws_message(SseDeserializer deserializer);

  @protected
  MiningPool sse_decode_mining_pool(SseDeserializer deserializer);

  @protected
  MoonPayCurrencyLimits sse_decode_moon_pay_currency_limits(
      SseDeserializer deserializer);

  @protected
  MoonPayEncryptedData sse_decode_moon_pay_encrypted_data(
      SseDeserializer deserializer);

  @protected
  MoonPayQuote sse_decode_moon_pay_quote(SseDeserializer deserializer);

  @protected
  OffchainBalance sse_decode_offchain_balance(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  BlockExtras? sse_decode_opt_box_autoadd_block_extras(
      SseDeserializer deserializer);

  @protected
  BoltzSwap? sse_decode_opt_box_autoadd_boltz_swap(
      SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  Conversions? sse_decode_opt_box_autoadd_conversions(
      SseDeserializer deserializer);

  @protected
  DifficultyAdjustment? sse_decode_opt_box_autoadd_difficulty_adjustment(
      SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  FearGreedData? sse_decode_opt_box_autoadd_fear_greed_data(
      SseDeserializer deserializer);

  @protected
  FearGreedLastUpdated? sse_decode_opt_box_autoadd_fear_greed_last_updated(
      SseDeserializer deserializer);

  @protected
  FearGreedValue? sse_decode_opt_box_autoadd_fear_greed_value(
      SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  MiningPool? sse_decode_opt_box_autoadd_mining_pool(
      SseDeserializer deserializer);

  @protected
  RecommendedFees? sse_decode_opt_box_autoadd_recommended_fees(
      SseDeserializer deserializer);

  @protected
  TxOutput? sse_decode_opt_box_autoadd_tx_output(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  List<Block>? sse_decode_opt_list_block(SseDeserializer deserializer);

  @protected
  List<MempoolBlock>? sse_decode_opt_list_mempool_block(
      SseDeserializer deserializer);

  @protected
  PaymentReceived sse_decode_payment_received(SseDeserializer deserializer);

  @protected
  ProjectedBlockTransactions sse_decode_projected_block_transactions(
      SseDeserializer deserializer);

  @protected
  ProjectedTransaction sse_decode_projected_transaction(
      SseDeserializer deserializer);

  @protected
  RecommendedFees sse_decode_recommended_fees(SseDeserializer deserializer);

  @protected
  (String, double) sse_decode_record_string_f_64(SseDeserializer deserializer);

  @protected
  Transaction sse_decode_transaction(SseDeserializer deserializer);

  @protected
  TxInput sse_decode_tx_input(SseDeserializer deserializer);

  @protected
  TxOutput sse_decode_tx_output(SseDeserializer deserializer);

  @protected
  TxStatus sse_decode_tx_status(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_Map_String_f_64_None(
      Map<String, double> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_log_entry_Sse(
      RustStreamSink<LogEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_mempool_ws_message_Sse(
      RustStreamSink<MempoolWsMessage> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_projected_block_transactions_Sse(
      RustStreamSink<ProjectedBlockTransactions> self,
      SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_addresses(Addresses self, SseSerializer serializer);

  @protected
  void sse_encode_balance(Balance self, SseSerializer serializer);

  @protected
  void sse_encode_bitcoin_transaction(
      BitcoinTransaction self, SseSerializer serializer);

  @protected
  void sse_encode_block(Block self, SseSerializer serializer);

  @protected
  void sse_encode_block_extras(BlockExtras self, SseSerializer serializer);

  @protected
  void sse_encode_boltz_swap(BoltzSwap self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_block_extras(
      BlockExtras self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_boltz_swap(
      BoltzSwap self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_conversions(
      Conversions self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_difficulty_adjustment(
      DifficultyAdjustment self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_fear_greed_data(
      FearGreedData self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_fear_greed_last_updated(
      FearGreedLastUpdated self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_fear_greed_value(
      FearGreedValue self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_mining_pool(
      MiningPool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_recommended_fees(
      RecommendedFees self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_tx_output(
      TxOutput self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_conversions(Conversions self, SseSerializer serializer);

  @protected
  void sse_encode_currency_info(CurrencyInfo self, SseSerializer serializer);

  @protected
  void sse_encode_difficulty_adjustment(
      DifficultyAdjustment self, SseSerializer serializer);

  @protected
  void sse_encode_difficulty_point(
      DifficultyPoint self, SseSerializer serializer);

  @protected
  void sse_encode_exchange_rates(ExchangeRates self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_fear_greed_data(FearGreedData self, SseSerializer serializer);

  @protected
  void sse_encode_fear_greed_index(
      FearGreedIndex self, SseSerializer serializer);

  @protected
  void sse_encode_fear_greed_last_updated(
      FearGreedLastUpdated self, SseSerializer serializer);

  @protected
  void sse_encode_fear_greed_value(
      FearGreedValue self, SseSerializer serializer);

  @protected
  void sse_encode_fiat_currency(FiatCurrency self, SseSerializer serializer);

  @protected
  void sse_encode_hashrate_data(HashrateData self, SseSerializer serializer);

  @protected
  void sse_encode_hashrate_point(HashratePoint self, SseSerializer serializer);

  @protected
  void sse_encode_historical_price_data(
      HistoricalPriceData self, SseSerializer serializer);

  @protected
  void sse_encode_historical_price_response(
      HistoricalPriceResponse self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_info(Info self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bitcoin_transaction(
      List<BitcoinTransaction> self, SseSerializer serializer);

  @protected
  void sse_encode_list_block(List<Block> self, SseSerializer serializer);

  @protected
  void sse_encode_list_difficulty_point(
      List<DifficultyPoint> self, SseSerializer serializer);

  @protected
  void sse_encode_list_fiat_currency(
      List<FiatCurrency> self, SseSerializer serializer);

  @protected
  void sse_encode_list_hashrate_point(
      List<HashratePoint> self, SseSerializer serializer);

  @protected
  void sse_encode_list_historical_price_data(
      List<HistoricalPriceData> self, SseSerializer serializer);

  @protected
  void sse_encode_list_mempool_block(
      List<MempoolBlock> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_f_64_strict(
      Float64List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_projected_transaction(
      List<ProjectedTransaction> self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_string_f_64(
      List<(String, double)> self, SseSerializer serializer);

  @protected
  void sse_encode_list_transaction(
      List<Transaction> self, SseSerializer serializer);

  @protected
  void sse_encode_list_tx_input(List<TxInput> self, SseSerializer serializer);

  @protected
  void sse_encode_list_tx_output(List<TxOutput> self, SseSerializer serializer);

  @protected
  void sse_encode_ln_payment_result(
      LnPaymentResult self, SseSerializer serializer);

  @protected
  void sse_encode_log_entry(LogEntry self, SseSerializer serializer);

  @protected
  void sse_encode_mempool_block(MempoolBlock self, SseSerializer serializer);

  @protected
  void sse_encode_mempool_ws_message(
      MempoolWsMessage self, SseSerializer serializer);

  @protected
  void sse_encode_mining_pool(MiningPool self, SseSerializer serializer);

  @protected
  void sse_encode_moon_pay_currency_limits(
      MoonPayCurrencyLimits self, SseSerializer serializer);

  @protected
  void sse_encode_moon_pay_encrypted_data(
      MoonPayEncryptedData self, SseSerializer serializer);

  @protected
  void sse_encode_moon_pay_quote(MoonPayQuote self, SseSerializer serializer);

  @protected
  void sse_encode_offchain_balance(
      OffchainBalance self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_block_extras(
      BlockExtras? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_boltz_swap(
      BoltzSwap? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_conversions(
      Conversions? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_difficulty_adjustment(
      DifficultyAdjustment? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_fear_greed_data(
      FearGreedData? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_fear_greed_last_updated(
      FearGreedLastUpdated? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_fear_greed_value(
      FearGreedValue? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_mining_pool(
      MiningPool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_recommended_fees(
      RecommendedFees? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_tx_output(
      TxOutput? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_block(List<Block>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_mempool_block(
      List<MempoolBlock>? self, SseSerializer serializer);

  @protected
  void sse_encode_payment_received(
      PaymentReceived self, SseSerializer serializer);

  @protected
  void sse_encode_projected_block_transactions(
      ProjectedBlockTransactions self, SseSerializer serializer);

  @protected
  void sse_encode_projected_transaction(
      ProjectedTransaction self, SseSerializer serializer);

  @protected
  void sse_encode_recommended_fees(
      RecommendedFees self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_f_64(
      (String, double) self, SseSerializer serializer);

  @protected
  void sse_encode_transaction(Transaction self, SseSerializer serializer);

  @protected
  void sse_encode_tx_input(TxInput self, SseSerializer serializer);

  @protected
  void sse_encode_tx_output(TxOutput self, SseSerializer serializer);

  @protected
  void sse_encode_tx_status(TxStatus self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;
}
