// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Simplified swap info for Flutter UI.
class SwapInfo {
  final String id;
  final SwapStatusSimple status;
  final String direction;
  final String sourceToken;
  final String targetToken;
  final PlatformInt64 sourceAmountSats;
  final double targetAmountUsd;
  final String createdAt;

  /// For BTC→EVM: Lightning invoice to pay
  final String? lnInvoice;

  /// For BTC→EVM: Arkade HTLC address
  final String? arkadeHtlcAddress;

  /// For EVM→BTC: EVM HTLC address to deposit to
  final String? evmHtlcAddress;

  /// Fee in satoshis
  final PlatformInt64 feeSats;

  const SwapInfo({
    required this.id,
    required this.status,
    required this.direction,
    required this.sourceToken,
    required this.targetToken,
    required this.sourceAmountSats,
    required this.targetAmountUsd,
    required this.createdAt,
    this.lnInvoice,
    this.arkadeHtlcAddress,
    this.evmHtlcAddress,
    required this.feeSats,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      status.hashCode ^
      direction.hashCode ^
      sourceToken.hashCode ^
      targetToken.hashCode ^
      sourceAmountSats.hashCode ^
      targetAmountUsd.hashCode ^
      createdAt.hashCode ^
      lnInvoice.hashCode ^
      arkadeHtlcAddress.hashCode ^
      evmHtlcAddress.hashCode ^
      feeSats.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SwapInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          status == other.status &&
          direction == other.direction &&
          sourceToken == other.sourceToken &&
          targetToken == other.targetToken &&
          sourceAmountSats == other.sourceAmountSats &&
          targetAmountUsd == other.targetAmountUsd &&
          createdAt == other.createdAt &&
          lnInvoice == other.lnInvoice &&
          arkadeHtlcAddress == other.arkadeHtlcAddress &&
          evmHtlcAddress == other.evmHtlcAddress &&
          feeSats == other.feeSats;
}

/// Simplified swap status for Flutter UI.
enum SwapStatusSimple {
  /// Waiting for user to deposit funds
  waitingForDeposit,

  /// User deposited, swap is processing
  processing,

  /// Swap completed successfully
  completed,

  /// Swap expired (no deposit)
  expired,

  /// Swap can be refunded
  refundable,

  /// Swap has been refunded
  refunded,

  /// Error state
  failed,
  ;
}
