// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<bool> walletExists({required String dataDir}) =>
    RustLib.instance.api.crateApiArkApiWalletExists(dataDir: dataDir);

Future<String> setupNewWallet({required String dataDir}) =>
    RustLib.instance.api.crateApiArkApiSetupNewWallet(dataDir: dataDir);

Future<String> loadExistingWallet({required String dataDir}) =>
    RustLib.instance.api.crateApiArkApiLoadExistingWallet(dataDir: dataDir);

Future<String> restoreWallet({required String nsec, required String dataDir}) =>
    RustLib.instance.api
        .crateApiArkApiRestoreWallet(nsec: nsec, dataDir: dataDir);
