// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models/historical_prices.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Fetch historical Bitcoin prices for a given time range.
Future<HistoricalPriceResponse> fetchHistoricalPrices({
  required String serverUrl,
  required String timeRange,
}) => RustLib.instance.api.crateApiBitcoinApiFetchHistoricalPrices(
  serverUrl: serverUrl,
  timeRange: timeRange,
);
