// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models/mempool.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `handle_projected_transactions`

/// Track a specific mempool block and stream its transactions
Stream<ProjectedBlockTransactions> trackMempoolBlock({
  required int blockIndex,
}) => RustLib.instance.api.crateApiMempoolBlockTrackerTrackMempoolBlock(
  blockIndex: blockIndex,
);
