// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models/moonpay.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Get currency limits for MoonPay transactions
Future<MoonPayCurrencyLimits> moonpayGetCurrencyLimits(
        {required String serverUrl,
        required String baseCurrencyCode,
        required String paymentMethod}) =>
    RustLib.instance.api.crateApiMoonpayApiMoonpayGetCurrencyLimits(
        serverUrl: serverUrl,
        baseCurrencyCode: baseCurrencyCode,
        paymentMethod: paymentMethod);

/// Get a quote from MoonPay
Future<MoonPayQuote> moonpayGetQuote({required String serverUrl}) =>
    RustLib.instance.api
        .crateApiMoonpayApiMoonpayGetQuote(serverUrl: serverUrl);

/// Encrypt data for MoonPay
Future<MoonPayEncryptedData> moonpayEncryptData(
        {required String serverUrl, required String data}) =>
    RustLib.instance.api
        .crateApiMoonpayApiMoonpayEncryptData(serverUrl: serverUrl, data: data);
